### ISSUE TITLE
Support for vtsls

### ISSUE THREAD

**Issue by kristijanhusak** [dmmulroy/ts-error-translator.nvim#16]
Hey!

Nice plugin! I'm hoping to get more understanding from those nasty TS errors.

I tried using this with my [vtsls](https://github.com/yioneko/nvim-vtsls) language server, but it didn't work. Once I updated the check for `client` to be `client == 'tsserver' or client == 'vtsls'` it started working.
Could that be added ?

**Comment by dmmulroy** [comment]
I'm unfamiliar with `vtsls`, but in the mean time you should be able to manually override `vtsls`'s `[textDocument]/publishDiagnostics` handler with the `require('ts-error-translator').translate` function.
