### ISSUE TITLE
What should i do to see the error "window"

### ISSUE THREAD

**Issue by danyalutsevich** [dmmulroy/ts-error-translator.nvim#29]
When Im draggin my cursor over the line with error the "window" with error do not show up
what am I doin wrong?
<img width="973" alt="Screenshot 2024-10-05 at 23 47 43" src="https://github.com/user-attachments/assets/e2dd1cec-0b58-485f-95ec-dcfaf663660a">

**Comment by pmwals09** [comment]
If I had to guess, you aren't triggering the "hover" function. See here: https://neovim.io/doc/user/lsp.html#vim.lsp.buf.hover()

Not sure how experienced you are w/ neovim - a "hover" with the terminal cursor isn't like a "hover" with the mouse cursor in VSCode. You need to trigger a "hover" action, which `vim.lsp.buf.hover()` does. I think the default keybind is "K" in insert mode. You can also type `:lua vim.lsp.buf.hover()` to trigger it manually.

**Comment by danyalutsevich** [comment]
forgot to try "K" but still dont work
if that helps there is my config [https://github.com/danyalutsevich/nvim/blob/base/lua/plugins/ts-error-translator.lua](https://github.com/danyalutsevich/nvim/blob/base/lua/plugins/ts-error-translator.lua)

**Comment by danyalutsevich** [comment]
it it shows only type description

<img width="1275" alt="Screenshot 2024-10-06 at 01 36 21" src="https://github.com/user-attachments/assets/a9d4bd04-6f28-4a37-bbfd-7d48cbb0daa9">

**Comment by danyalutsevich** [comment]
@pmwals09 any ideas?
thank you in advice

**Comment by bren-do** [comment]
I seem to have the same issue. In my setup, based very heavily on kickstart.nvim, `vim.lsp.buf.hover()` returns type information instead of the error translation. 
I have included the plugin with all defaults, and am using `vtsls` as my LSP. Is there anything we need to do to manage which of these behaviours is triggered by `K`?

**Comment by bren-do** [comment]
@danyalutsevich I figured it out. It's not triggered by `hover()`, it's triggered by `lua vim.diagnostic.open_float()`

**Comment by danyalutsevich** [comment]
@bren-do oh thanks man. It works

**Comment by danyalutsevich** [comment]
i think this issue can be closed
