### ISSUE TITLE
In neovim nightly lsp handlers no longer accept config parameter

### ISSUE THREAD

**Issue by catgoose** [dmmulroy/ts-error-translator.nvim#30]
See https://github.com/neovim/neovim/pull/30982/commits/6841a0c484f4bf4b0b1df5271eff90ebc25f78c5

New implementation should (I think) be something like

```lua
vim.lsp.handlers["textDocument/publishDiagnostics"] = function(err, result, ctx)
  require("ts-error-translator").translate_diagnostics(err, result, ctx)
  vim.lsp.diagnostic.on_publish_diagnostics(err, result, ctx)
end
```

**Comment by dmmulroy** [comment]
Hey if you could open a PR I'd be happy to merge - don't have a lot of time to work on this atm unfortunately

**Comment by catgoose** [comment]
I can do that
